### ISSUE TITLE
support other IntelliJ-based products

### ISSUE THREAD

**Issue by mier85** [jeysal/livetemplate-scriptengine-macro#1]
Hi, thanks for your work on this! I was looking for exactly this. I am not using Intellij for that long ( currently using gogland 1.0 EAP ). So I installed the plugin and then created a live template and just copy/pasted your example. Then when I triggered the live template, I didn't get any output. 

Are there any logs that I can access to see what's the issue or do I need to install any other dependency to make it work?

Edit: 
So I installed the intellij community edition and tried the same in a java project and it actually worked. So I guess it is something related to gogland. I will see if i can find some log for it somewhere

**Comment by jeysal** [comment]
Hi, thanks for trying out the plugin!

As for logs, most of the stuff that can go wrong will just print out an error message in the editor when inserting the template.
If the plugin actually breaks down, you should see an error popup in the bottom right corner of the IDE, at least that's what would happen in IntelliJ IDEA.

Can you check if the expression field where you entered the `script(...)` offers the entry `script("path or language:code", args...)` in its dropdown menu? Maybe Gogland simply doesn't find the macro.

**Comment by mier85** [comment]
Thanks for your quick reply! It's not in the dropdown menu (it is in the community edition). So it seems like you are right and it is not even loaded. I see it in the plugin list though, and it is enabled.

**Comment by jeysal** [comment]
I'm pretty sure the problem was just that I forgot to specify the compatibilty with other IntelliJ-based JetBrains products such as Gogland as described [here](http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html), causing Gogland to ignore the macro that the plugin usually supplies.

I've released version 1.2.1, which will hopefully fix the plugin for your IDE and others.
The update should be showing up in your IDE soon.

Please tell me if it now works for you once you've tried it.

**Comment by jeysal** [comment]
Whoops, didn't wanna close the issue just yet. Guess we can just reopen it if there's still a problem, though ;)

**Comment by mier85** [comment]
Thank you! It works like a charm now! This will save me a lot of typing time in the future!
